language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements-dev.txt
before_script:
  - pip install coveralls PyYAML
script:
  - ENVIRONMENT=test coverage run $(which pytest)
after_success:
  - coveralls
